---
version: '3'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${TAG}
    environment: ['http.host=0.0.0.0', 'transport.host=127.0.0.1']
    ports: ['127.0.0.1:9200:9200']
    networks: ['stack']

  kibana:
    image: docker.elastic.co/kibana/kibana:${TAG}
    ports: ['127.0.0.1:5601:5601']
    networks: ['stack']
    depends_on: ['elasticsearch']

  logstash:
    image: docker.elastic.co/logstash/logstash:${TAG}
    volumes:
      - ./config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks: ['stack']
    depends_on: ['elasticsearch']

  filebeat:
    image: docker.elastic.co/beats/filebeat:${TAG}
    networks: ['stack']
    depends_on: ['elasticsearch']

  heartbeat:
    image: docker.elastic.co/beats/heartbeat:${TAG}
    networks: ['stack']
    depends_on: ['elasticsearch']

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:${TAG}
    command: metricbeat -e
    networks: ['stack']
    depends_on: ['elasticsearch']

  packetbeat:
    image: docker.elastic.co/beats/packetbeat:${TAG}
    cap_add: ['NET_RAW', 'NET_ADMIN']
    network_mode: host
    command: packetbeat -v -e -E output.elasticsearch.hosts='["localhost:9200"]'
    depends_on: ['elasticsearch']
    
  configure_kibana:
    image: docker.elastic.co/beats/metricbeat:${TAG}
    volumes: ['./scripts/configure-kibana.sh:/usr/local/bin/configure-kibana.sh:ro']
    command: ['/bin/bash', '-c', 'cat /usr/local/bin/configure-kibana.sh | tr -d "\r" | bash']
    environment: ['ELASTIC_VERSION=${ELASTIC_VERSION}']
    networks: ['stack']
    depends_on: ['kibana']

networks: {stack: {}}
